export 'package:widget_formatos/presentation/screens/animated/animated_screen.dart';
export 'package:widget_formatos/presentation/screens/app_tutorial/app_tutorial_screen.dart';
export 'package:widget_formatos/presentation/screens/buttons/buttons_screens.dart';
export 'package:widget_formatos/presentation/screens/cards/cards_screen.dart';
export 'package:widget_formatos/presentation/screens/home/home_screen.dart';
export 'package:widget_formatos/presentation/screens/infinite_scroll/infinite_scroll_screen.dart';
export 'package:widget_formatos/presentation/screens/progress/progress.dart';
export 'package:widget_formatos/presentation/screens/snapbar/snackbar_screen.dart';
export 'package:widget_formatos/presentation/screens/ui_controls/ui_controls_screen.dart';